FROM jenkins/jenkins:2.375.3
USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
RUN apt install junit -y
RUN apt-get install wget -y
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.0/binaries/apache-maven-3.9.0-bin.tar.gz
RUN tar xvfz apache-maven-3.9.0-bin.tar.gz -C /opt
RUN ln -s /opt/apache-maven-3.9.0 /opt/maven
RUN echo "export M2_HOME=/opt/maven" > /etc/profile.d/maven.sh
RUN echo "export MAVEN_HOME=/opt/maven" >> /etc/profile.d/maven.sh
RUN echo "export PATH=/opt/maven/bin:${PATH}" >> /etc/profile.d/maven.sh
RUN chmod 755 /etc/profile.d/maven.sh
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"

