pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '. /etc/profile.d/maven.sh; pwd; ls -al; mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '. /etc/profile.d/maven.sh; pwd; ls -al; mvn test'
            }
            //post {
            //    always {
            //        sh '. /etc/profile.d/maven.sh; pwd; ls -al; junit target/surefire-reports/*.xml'
            //    }
            //}
        }
        stage('Deliver') {
            steps {
                sh '. /etc/profile.d/maven.sh; pwd; ls -al; ./jenkins/scripts/deliver.sh'
            }
        }
        stage('Last Stage') {
            steps {
                sh 'echo Finished!!!!Jenkinsfile'
            }
        }
    }
}
